storageClassName: 
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20:10:16

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script: 
    - docker build -t victorfg21/kubernetes-cicd-dio-challenge:1.0 app/.
    - docker push victorfg21/kubernetes-cicd-dio-challenge:1.0

deploy_gcp:
  stage: deploy_gcp
  
  before_script:
    - chmod 400 $SSH_KEY

  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -Rf ./kubernetes-cicd-dio-challenge/ && sudo git clone https://gitlab.com/victorfg21/kubernetes-cicd-dio-challenge.git && cd kubernetes-cicd-dio-challenge && sudo chmod +x ./script.sh && ./script.sh"